### ISSUE TITLE
Build and publish a Docker image to improve GH action runtime

### ISSUE THREAD

**Issue by mark-ebot7** [ebot7/eb7-sls-helper#8]
Currently building the image takes close to two minutes. This could be decreased significantly by publishing the image on Dockerhub, so that we just have to pull the image.

**Comment by paolo-rechia** [comment]
Opened PX ticket to provide this: https://eb7team.atlassian.net/browse/PX-873

**Comment by paolo-rechia** [comment]
Fixed by https://github.com/ebot7/eb7-sls-helper/pull/17
